"""Generate the UNPIVOT SQL for every wide Zillow table from the CSV headers.

All four Zillow files are wide: ID columns + one column per month. BigQuery's UNPIVOT
needs every month column named explicitly; at ~320 columns for ZHVI that list is
generated, not hand-typed (the documented pattern for large unpivots — the alternative
is hand-writing the IN-list). BigQuery flexible column names keep the headers verbatim
(`2000-01-31`), so the generated list backticks each name and UNPIVOT's label string
parses directly with PARSE_DATE. UNPIVOT drops NULL cells by design (sparse early
years). Autodetect types RegionName as INTEGER, dropping leading zeros on northeastern
zips — the ZHVI SELECT pads them back to 5 digits.
"""

import csv
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# (csv file, raw table, target table, value column, SELECT list for ID columns)
TABLES = [
    ("Zip_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv",
     "raw.zhvi_zip", "marts.zhvi_long", "zhvi",
     ["LPAD(CAST(RegionName AS STRING), 5, '0') AS zip_code", "State AS state",
      "Metro AS metro", "CountyName AS county"]),
    ("Metro_median_sale_price_uc_sfrcondo_sm_sa_month.csv",
     "raw.median_sale_price", "marts.sale_price_long", "median_sale_price",
     ["RegionName AS metro", "RegionType AS region_type", "StateName AS state"]),
    ("Metro_mlp_uc_sfrcondo_sm_month.csv",
     "raw.median_list_price", "marts.list_price_long", "median_list_price",
     ["RegionName AS metro", "RegionType AS region_type", "StateName AS state"]),
    ("Metro_perc_listings_price_cut_uc_sfrcondo_sm_month.csv",
     "raw.price_cut_share", "marts.price_cut_long", "price_cut_share",
     ["RegionName AS metro", "RegionType AS region_type", "StateName AS state"]),
]

ID_COLUMNS = {"RegionID", "SizeRank", "RegionName", "RegionType",
              "StateName", "State", "City", "Metro", "CountyName"}


def bq_column_name(header: str) -> str:
    return f"`{header}`"


def main() -> None:
    statements = []
    for csv_name, raw_table, target, value_col, id_select in TABLES:
        with open(REPO / "data" / csv_name, newline="") as f:
            header = next(csv.reader(f))
        month_cols = [bq_column_name(h) for h in header if h not in ID_COLUMNS]
        if not month_cols:
            raise SystemExit(f"No month columns in {csv_name} — layout changed?")

        id_list = ",\n  ".join(id_select)
        col_list = ",\n    ".join(month_cols)
        statements.append(
            f"-- {csv_name}: {len(month_cols)} month columns "
            f"({month_cols[0]} .. {month_cols[-1]})\n"
            f"CREATE OR REPLACE TABLE {target} AS\n"
            f"SELECT\n  {id_list},\n"
            f"  PARSE_DATE('%Y-%m-%d', month_col) AS month,\n"
            f"  {value_col}\n"
            f"FROM {raw_table}\n"
            f"UNPIVOT ({value_col} FOR month_col IN (\n    {col_list}\n));\n"
        )
        print(f"{target}: {len(month_cols)} month columns")

    sql_path = REPO / "sql" / "01_unpivot_zhvi.sql"
    sql_path.write_text(
        "-- Generated by python/generate_unpivot_sql.py -- do not edit by hand.\n"
        "-- Unpivots all four wide Zillow tables into long format.\n\n"
        + "\n".join(statements),
        encoding="utf-8",
    )
    print(f"Wrote {sql_path}")


if __name__ == "__main__":
    main()
